# ---------------------------------------------------------------
# 35-china-direct.ps1 - 内置「国内常见域名」直连清单
# ---------------------------------------------------------------
# 内置 PAC 的「智能分流」策略用它判断哪些域名直连，
# 不在清单里的全部交给用户的代理（代理自己还有一层分流规则），
# 所以这里只需要覆盖常见站，不必求全。
#
# 本文件由 tools/gen-china-list.py 生成，请勿手工大改。
# 重新生成： python tools/gen-china-list.py
#
# 数据来源（三源交叉确认，均为公开数据）：
#   felixonmars/dnsmasq-china-list  accelerated-domains.china.conf
#   blackmatrix7/ios_rule_script    ChinaMax
#   ACL4SSR/ACL4SSR                 ChinaDomain.list
# ---------------------------------------------------------------

$script:ChinaDirectDomains = @(
    '00cdn.com', '10010.com', '115.com', '12306.cn', '12306.com', '126.com',
    '126.fm', '126.net', '127.net', '13th.tech', '163.cm', '163.com',
    '163.fm', '163.gg', '163.lu', '163.net', '163yun.com', '1688.com',
    '17173.com', '178.com', '17k.com', '21cn.com', '360.com', '360buy.com',
    '360buyimg.com', '360doc.com', '360kuai.com', '360safe.com', '36kr.com', '3dmgame.com',
    '423down.com', '4399.com', '4399pk.com', '5054399.com', '51cto.com', '51job.com',
    '51jobcdn.com', '56.com', '58.com', '71edge.com', '8686c.com', '88cdn.com',
    '95516.com', 'abchina.com', 'abercrombie.com', 'acfun.tv', 'acg.tv', 'acgvideo.com',
    'air-matters.com', 'air-matters.io', 'aixifan.com', 'aliapp.org', 'alibaba.com', 'alibaba.net',
    'alibabachengdun.com', 'alibabacloud.com', 'alibabausercontent.com', 'alicdn.com', 'alicloudccp.com', 'aliexpress.com',
    'aliimg.com', 'alikunlun.com', 'alipay.com', 'alipay.hk', 'alipay.net', 'alipayobjects.com',
    'alisoft.com', 'aliyun.com', 'aliyun.org', 'aliyun.xin', 'aliyuncdn.com', 'aliyuncs.com',
    'aliyundrive.cloud', 'aliyundrive.com', 'aliyundrive.net', 'allawnfs.com', 'allawno.com', 'allawntech.com',
    'amap.com', 'amemv.com', 'amemv.net', 'appsimg.com', 'appvipshop.com', 'asklink.com',
    'auth.wo.cn', 'auth.wosms.cn', 'autohome.com', 'autonavi.com', 'b23.tv', 'babytree.com',
    'babytreeimg.com', 'baicizhan.com', 'baidu.cc', 'baidu.com', 'baidu.mobi', 'baidubcr.com',
    'baidupan.com', 'baidupcs.com', 'baidustatic.com', 'baike.com', 'baomitu.com', 'bcebos.com',
    'bdimg.com', 'bdstatic.com', 'bdurl.net', 'bdxiguaimg.com', 'bdxiguastatic.com', 'bigfun.cn',
    'bigfunapp.cn', 'biliapi.com', 'biliapi.net', 'bilibili.cc', 'bilibili.co', 'bilibili.com',
    'bilibili.li', 'bilibili.net', 'biligame.com', 'biligame.net', 'biliintl.co', 'bilivideo.cn',
    'bilivideo.com', 'bilivideo.net', 'biqudu.com', 'bitauto.com', 'bokecc.com', 'bootcss.com',
    'bosszhipin.com', 'byted-static.com', 'bytedance.com', 'bytedance.net', 'bytedance.org', 'bytedns.net',
    'bytednsdoc.com', 'bytefcdnrd.com', 'bytegoofy.com', 'byteimg.com', 'bytescm.com', 'bytetos.com',
    'bytexservice.com', 'c-ctrip.com', 'camera360.com', 'ccb.com', 'cctv.com', 'cctvpic.com',
    'cdnmama.com', 'ceair.com', 'chaoxing.com', 'che168.com', 'chinacache.net', 'chinaso.com',
    'chinaunicom.com', 'chinaz.com', 'chinaz.net', 'chuimg.com', 'cibntv.net', 'clouddn.com',
    'cloudxns.net', 'cmbchina.biz', 'cmbchina.com', 'cmbchina.net', 'cmpassport.com', 'cn',
    'cnblogs.com', 'cnblogs.vip', 'cnki.net', 'cnmstl.net', 'coloros.com', 'config.cmpassport.com',
    'coolapk.com', 'coolapkmarket.com', 'csdn.com', 'csdn.net', 'csdn.work', 'csgo.wmsj.cn',
    'ctrip.co.id', 'ctrip.co.kr', 'ctrip.com', 'ctrip.my', 'ctrip.sg', 'dangdang.com',
    'dbankcdn.com', 'dfcfw.com', 'dhrest.com', 'dianping.com', 'didi.xin', 'didialift.com',
    'didiglobal.com', 'dilidili.wang', 'dingtalk.co.jp', 'dingtalk.com', 'dingtalk.io', 'dingtalk.net',
    'dns.alidns.com', 'dnspod.com', 'dnspod.mobi', 'dnspod.net', 'dnspod.org', 'doh.360.cn',
    'doh.pub', 'dongchedi.com', 'dota2.wmsj.cn', 'douban.com', 'douban.fm', 'doubanio.com',
    'douyin.com', 'douyincdn.com', 'douyinpic.com', 'douyinstatic.com', 'douyinvod.com', 'douyu.com',
    'douyu.tv', 'douyucdn.cn', 'douyuscdn.com', 'douyutv.com', 'dpfile.com', 'duokan.com',
    'duowan.com', 'dxycdn.com', 'dytt8.net', 'easou.com', 'eastday.com', 'eastmoney.com',
    'ecitic.com', 'edgesrv.com', 'ele.me', 'ele.to', 'elemecdn.com', 'elong.com',
    'elong.net', 'enrichgw.10010.com', 'ewqcxz.com', 'fang.com', 'feelgood.cn', 'feiliao.com',
    'feishu.cn', 'feishu.net', 'feng.com', 'fengkongcloud.com', 'fir.im', 'foxmail.com',
    'frdic.com', 'fresh-ideas.cc', 'ganji.com', 'ganjistatic1.com', 'geetest.com', 'geilicdn.com',
    'ghpym.com', 'gifshow.com', 'gitee.com', 'gitee.io', 'go2map.com', 'godic.net',
    'got001.com', 'gtimg.com', 'guazi.com', 'gwdang.com', 'gzlzfm.com', 'haibian.com',
    'hao123.com', 'hao123.com.sg', 'hao123.net', 'hao123.ph', 'hao123img.com', 'haosou.com',
    'hc-cdn.com', 'hdslb.com', 'hdslb.net', 'hdslb.org', 'heytap.com', 'heytapcs.com',
    'heytapdownload.com', 'heytapimage.com', 'heytapmobi.com', 'hichina.com', 'hicloud.com', 'hihonor.com',
    'hitv.com', 'hmrz.wo.cn', 'hollisterco.com', 'hongxiu.com', 'huajiao.com', 'huawei.asia',
    'huawei.com', 'huawei.eu', 'huawei.ru', 'huaweicloud.com', 'huaweishop.net', 'hunantv.com',
    'huoshan.cc', 'huoshan.club', 'huoshan.com', 'huoshanzhibo.com', 'hupu.com', 'hupu.io',
    'huxiucdn.com', 'huya.com', 'hwccpc.com', 'ibytedapm.com', 'icbc.ae', 'icbc.be',
    'icbc.jp', 'iciba.com', 'id.mail.wo.cn', 'id6.me', 'idqqimg.com', 'iesdouyin.com',
    'ifeng.com', 'ifengimg.com', 'iflyink.com', 'iflyrec.com', 'iflytek.com', 'igamecj.com',
    'im9.com', 'images-amazon.com', 'img4399.com', 'infzm.com', 'ipip.net', 'iqiyi.com',
    'iqiyipic.com', 'it168.com', 'ithome.com', 'ixdzs.com', 'ixigua.com', 'jcloudcs.com',
    'jd.co', 'jd.com', 'jd.hk', 'jd.shop', 'jdcloud.com', 'jdpay.com',
    'jianguoyun.com', 'jianshu.com', 'jianshu.io', 'jianshuapi.com', 'jiasule.com', 'jingdong.com',
    'jmstatic.com', 'jomodns.com', 'juejin.cn', 'jumei.com', 'kaikeba.com', 'kanimg.com',
    'kankan.com', 'kaola.com', 'kingsoft.com', 'kingsoft.net', 'knewone.com', 'koowo.com',
    'ksosoft.com', 'kspkg.com', 'ksyun.com', 'ksyungslb.com', 'kuaidi100.com', 'kuaishou.com',
    'kugou.com', 'kugou.net', 'lagou.com', 'landiannews.com', 'lanzou.com', 'lanzoui.com',
    'lanzoux.com', 'laomo.me', 'le.com', 'lecloud.com', 'leju.com', 'lemicp.com',
    'letv.com', 'letvcloud.com', 'letvimg.com', 'letvlive.com', 'letvstore.com', 'livechina.com',
    'lizhi.fm', 'lizhi.io', 'lizhifm.com', 'lofter.com', 'log.cmpassport.com', 'log1.cmpassport.com',
    'luoo.net', 'lvmama.com', 'lxdns.com', 'maoyan.com', 'mdn.open.wo.cn', 'meilishuo.com',
    'meipai.com', 'meitu.com', 'meituan.com', 'meituan.net', 'meitudata.com', 'meitustat.com',
    'meizu.com', 'mgtv.com', 'mi-img.com', 'mi.com', 'miaopai.com', 'migu.store',
    'migucloud.com', 'miguvideo.com', 'miui.com', 'mmstat.com', 'mob.com', 'mobike.com',
    'mogu.com', 'mogucdn.com', 'mogujie.com', 'moji.com', 'moke.com', 'msstatic.com',
    'mubu.com', 'mxhichina.com', 'myapp.com', 'myqcloud.com', 'myunlu.com', 'netease.com',
    'netease.im', 'nishub1.10010.com', 'nodeseek.com', 'nruan.com', 'nuomi.com', 'onedns.net',
    'oneplus.com', 'onlinedown.net', 'open.e.189.cn', 'opencloud.wostore.cn', 'oppo.com', 'oppoer.me',
    'oppomobile.com', 'oracle.com', 'oschina.com', 'oschina.io', 'oschina.net', 'ourdvs.com',
    'p2cdn.com', 'p4pfile.com', 'paipai.com', 'pconline.com.cn', 'pddpic.com', 'pinduoduo.com',
    'pinduoduo.net', 'polyv.net', 'pplive.com', 'ppsimg.com', 'pptv.com', 'pstatp.com',
    'qbox.me', 'qcc.com', 'qcc.qualcomm.com', 'qcloud.com', 'qcloud.la', 'qcloudcdn.com',
    'qdaily.com', 'qdmm.com', 'qhimg.com', 'qhres.com', 'qhstatic.com', 'qhupdate.com',
    'qianqian.com', 'qidian.com', 'qihucdn.com', 'qin.io', 'qingting.fm', 'qiniu.com',
    'qiniucdn.com', 'qiniudn.com', 'qiushibaike.com', 'qiyi.com', 'qiyi.video', 'qiyipic.com',
    'qq.cc', 'qq.com', 'qq.design', 'qq.do', 'qq.md', 'qq.net',
    'qq.travel', 'qq.zone', 'qqmail.com', 'qqmail.email', 'qqurl.com', 'quanmin.tv',
    'qunar.com', 'qunar.ink', 'qunarzz.com', 'qwen.ai', 'qy.net', 'realme.com',
    'rrys.tv', 'rrys2020.com', 'ruguoapp.com', 'runoob.com', 'sandai.net', 'sankuai.com',
    'segmentfault.com', 'segmentfault.net', 'sf-express.com', 'sina.cn', 'sina.com', 'sina.com.cn',
    'sina.lt', 'sina.net', 'sinaapp.cn', 'sinaapp.com', 'sinaimg.cn', 'sinaimg.com',
    'smtcdns.com', 'smtcdns.net', 'smzdm.com', 'snapdrop.net', 'snssdk.com', 'snwx.com',
    'so.com', 'sogo.com', 'sogou.com', 'sogoucdn.com', 'sohu-inc.com', 'sohu.com',
    'sohu.net', 'sohucs.com', 'sohurdc.com', 'soku.com', 'sony.com', 'sonyentertainmentnetwork.com',
    'soso.com', 'soufunimg.com', 'sspai.com', 'st.dl.bscstorage.net', 'st.dl.eccdnx.com', 'startssl.com',
    'staticfile.org', 'steamchina.com', 'steampowered.com.8686c.com', 'steamstatic.com.8686c.com', 'suning.com', 'taihe.com',
    'taobao.com', 'taobao.global', 'taobao.net', 'taobao.org', 'taobao.tw', 'taobaocdn.com',
    'tbcache.com', 'tbcdn.cn', 'tbcdn.com', 'tencent-cloud.net', 'tencent.co.id', 'tencent.com',
    'tencent.com.hk', 'tencent.design', 'tencent.net', 'tencentmind.com', 'tencentmusic.com', 'tenpay.com',
    'th-sjy.com', 'thundercdn.com', 'tianqi.com', 'tianqistatic.com', 'tianyancha.com', 'tianyancha.net',
    'tianyaui.com', 'tietuku.com', 'tiexue.net', 'tmall.com', 'tmall.hk', 'tmall.ru',
    'toutiao.com', 'toutiao.org', 'toutiao13.com', 'toutiaoapi.com', 'toutiaocdn.com', 'toutiaocdn.net',
    'toutiaocloud.com', 'toutiaohao.com', 'toutiaohao.net', 'toutiaoimg.com', 'toutiaopage.com', 'trip.com',
    'ttmeiju.com', 'tudou.com', 'tuna.tsinghua.edu.cn', 'tuniu.com', 'tuniucdn.com', 'ucweb.com',
    'udache.com', 'umeng.co', 'umeng.com', 'umengcloud.com', 'upaiyun.com', 'upyun.com',
    'uxengine.net', 'v-56.com', 'v2ex.com', 'videocc.net', 'vip.com', 'vipstatic.com',
    'vivo.com', 'vivo.xyz', 'vmall.com', 'vmallres.com', 'volcengine.com', 'volcengine.net',
    'wandoujia.com', 'weather.com', 'wechat.com', 'wechat.design', 'wechat.org', 'weibo.cn',
    'weibo.com', 'weibo.tv', 'weibocdn.cn', 'weibocdn.com', 'weico.cc', 'weidian.com',
    'weiphone.com', 'weiphone.net', 'weixin.com', 'weiyun.com', 'womai.com', 'wps.cn',
    'wscdns.com', 'wukong.com', 'xdrig.com', 'xhscdn.com', 'xhscdn.net', 'xiachufang.com',
    'xiami.com', 'xiami.net', 'xiaohongshu.com', 'xiaohongshu.net', 'xiaojukeji.com', 'xiaoka.tv',
    'xiaomi.com', 'xiaomi.hk', 'xiaomi.net', 'xiaomi.org', 'xiaomi.tw', 'xiaomicp.com',
    'ximalaya.com', 'ximalaya.fm', 'ximalaya.men', 'ximalaya.tv', 'xinhuanet.com', 'xitek.com',
    'xiumi.us', 'xmcdn.com', 'xn--55qx5d', 'xn--fiqs8s', 'xn--io0a7i', 'xslb.net',
    'xueqiu.com', 'xunlei.com', 'xunlei.net', 'xz.pphimalayanrt.com', 'yach.me', 'yangkeduo.com',
    'ydstatic.com', 'ye.dun.163yun.com', 'yeah.net', 'yeepay.com', 'yhd.com', 'yiche.com',
    'yihaodianimg.com', 'yinxiang.com', 'yinyuetai.com', 'yixia.com', 'ykimg.com', 'youdao.com',
    'youku.com', 'youku.icu', 'ys168.com', 'yuewen.com', 'yunjiasu-cdn.net', 'yunpan.com',
    'yuque.com', 'yximgs.com', 'yy.com', 'yyets.com', 'yystatic.com', 'zealer.com',
    'zhangzishi.cc', 'zhanqi.tv', 'zhaopin.com', 'zhenguanyu.biz', 'zhenguanyu.com', 'zhihu.com',
    'zhihu.dev', 'zhimg.com', 'zhipin.com', 'zhongsou.com', 'zhuihd.com', 'zijieapi.com',
    'zijieimg.com', 'zimuzu.io', 'zimuzu.tv', 'zjbyte.com', 'zjcdn.com', 'zmz001.com',
    'zmz002.com', 'zmz003.com', 'zmz004.com', 'zmz2019.com', 'zmzapi.com', 'zmzapi.net',
    'zol.com.cn'
)

# .cn 全域直连（政务 / 学校 / 银行 / 大量国内站点都在这个后缀下）
$script:ChinaDirectSuffixes = @('.cn')
